
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author urmikapoor
 */
public class Main extends javax.swing.JFrame {

     Connection con=null;
        ResultSet rs=null;
        PreparedStatement pst=null;   
    
        public static Connection ConnectDB()
    {
        
        try
        {
            Class.forName("org.sqlite.JDBC");
            Connection con1=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\urmikapoor\\Desktop\\IDF2.sqlite");
            JOptionPane.showMessageDialog(null, "ConnectionEstablished");
            return con1;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        return null;    
    }
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        con=ConnectDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Gender:");

        jLabel4.setText("Session:");

        jLabel5.setText("Punctuality:");

        jLabel6.setText("Leadership:");

        jLabel7.setText("Interaction:");

        jLabel8.setText("Neatness:");

        jLabel9.setText("Understanding:");

        jLabel10.setText("Politeness:");

        jLabel11.setText("Code Of Conduct:");

        jLabel12.setText("Pronunciation:");

        jLabel13.setText("Clarity:");

        jLabel14.setText("Confidence:");

        jLabel15.setText("Communication Of Ideas:");

        jLabel16.setText("Originality:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Discipline:");

        jButton5.setText("View Rankings");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Session ID:");

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jLabel19.setText("Order by:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pointer", "Punctuality", "Discipline", "Leadership", "Interaction", "Neatness", "Understanding", "Politeness", "Code_Of_Conduct", "Pronunciation", "Clarity", "Confidence", "Communication_Of_Ideas", "Originality" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ascending", "Descending" }));

        jButton6.setText("Student Progress");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setText("Chart Type:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pie Chart", "Bar Chart", "Line Chart" }));

        jLabel21.setText("Attribute:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pointer", "Punctuality", "Discipline", "Leadership", "Interaction", "Neatness", "Understanding", "Politeness", "Code_Of_Conduct", "Pronunciation", "Clarity", "Confidence", "Communication_Of_Ideas", "Originality" }));

        jButton7.setText("Student Marks Allocation");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel22.setText("Chart Type:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pie Chart", "Bar Chart", "Line Chart" }));

        jLabel23.setText("Session No:");

        jLabel24.setText("ID:");

        jButton8.setText("Comparison");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel25.setText("Session Number:");

        jLabel26.setText("ID:");

        jLabel27.setText("V/S");

        jLabel28.setText("Session Number:");

        jLabel29.setText("ID:");

        jLabel30.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField16)
                    .addComponent(jTextField17))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField19))
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField25))))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField22))
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel18)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jLabel20)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)
                            .addComponent(jLabel22)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        int w=Integer.parseInt(jTextField5.getText());
        int w1=Integer.parseInt(jTextField17.getText());
        int w2=Integer.parseInt(jTextField6.getText());
        int w3=Integer.parseInt(jTextField7.getText());
        int w4=Integer.parseInt(jTextField8.getText());
        int w5=Integer.parseInt(jTextField9.getText());
        int w6=Integer.parseInt(jTextField10.getText());
        int w7=Integer.parseInt(jTextField11.getText());
        int w8=Integer.parseInt(jTextField12.getText());
        int w9=Integer.parseInt(jTextField13.getText());
        int w10=Integer.parseInt(jTextField14.getText());
        int w11=Integer.parseInt(jTextField15.getText());
        int w12=Integer.parseInt(jTextField16.getText());
        double pointer;
        String h=null;
        
         int sum=w1+w2+w+w3+w4+w5+w6+w7+w8+w9+w10+w11+w12;
        pointer=(double)((w*6)+(w1*7)+(w2*8)+(w3*8)+(w4*6)+(w5*10)+(w6*9)+(w7*9)+(w8*10)+(w9*10)+(w10*9)+(w11*8)+(w12*7))/1070;
        if(pointer>=9&&pointer<=10)
            h="Outstanding";
        else if(pointer>=8&&pointer<9)
            h="Excellent";
        else if(pointer>=7&&pointer<8)
            h="Good";
        else if(pointer>=6&&pointer<7)
            h="Average";
        else if(pointer>=5&&pointer<6)
            h="Poor";
        else if(pointer>=4&&pointer<5)
            h="Pass";
        else if(pointer<4)
            h="Fail";
   String insert="Insert into Student(ID,Name,Gender,Session,Punctuality,Discipline,Leadership,Interaction,Neatness,Understanding,Politeness,Code_Of_Conduct,Pronunciation,Clarity,Confidence,Communication_Of_Ideas,Originality,Pointer,Evaluation) values('"+jTextField2.getText()+"','"+jTextField1.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField17.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"','"+jTextField8.getText()+"','"+jTextField9.getText()+"', '"+jTextField10.getText()+"','"+jTextField11.getText()+"','"+jTextField12.getText()+"','"+jTextField13.getText()+"', '"+jTextField14.getText()+"', '"+jTextField15.getText()+"', '"+jTextField16.getText()+"','"+pointer+"','"+h+"')";
      
        try
        {
          pst=con.prepareStatement(insert);
          System.out.println(pst);
          pst.execute();
         // rs=pst.executeQuery();
          System.out.println(pst);
          JOptionPane.showMessageDialog(null,"Updated");
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
       e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  String delete="delete from student where ID='"+jTextField2.getText()+"' and Session='"+jTextField4.getText()+"'";    
        try
        {
          pst=con.prepareStatement(delete);
          System.out.println(pst);
          pst.execute();
         // rs=pst.executeQuery();
          
          JOptionPane.showMessageDialog(null,"Deleted");
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
       e.printStackTrace();
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
          int w=Integer.parseInt(jTextField5.getText());
        int w1=Integer.parseInt(jTextField17.getText());
        int w2=Integer.parseInt(jTextField6.getText());
        int w3=Integer.parseInt(jTextField7.getText());
        int w4=Integer.parseInt(jTextField8.getText());
        int w5=Integer.parseInt(jTextField9.getText());
        int w6=Integer.parseInt(jTextField10.getText());
        int w7=Integer.parseInt(jTextField11.getText());
        int w8=Integer.parseInt(jTextField12.getText());
        int w9=Integer.parseInt(jTextField13.getText());
        int w10=Integer.parseInt(jTextField14.getText());
        int w11=Integer.parseInt(jTextField15.getText());
        int w12=Integer.parseInt(jTextField16.getText());
        double pointer;
        String h=null;
        
         int sum=w1+w2+w+w3+w4+w5+w6+w7+w8+w9+w10+w11+w12;
        pointer=(double)((w*6)+(w1*7)+(w2*8)+(w3*8)+(w4*6)+(w5*10)+(w6*9)+(w7*9)+(w8*10)+(w9*10)+(w10*9)+(w11*8)+(w12*7))/1070;
        if(pointer>=9&&pointer<=10)
            h="Outstanding";
        else if(pointer>=8&&pointer<9)
            h="Excellent";
        else if(pointer>=7&&pointer<8)
            h="Good";
        else if(pointer>=6&&pointer<7)
            h="Average";
        else if(pointer>=5&&pointer<6)
            h="Poor";
        else if(pointer>=4&&pointer<5)
            h="Pass";
        else if(pointer<4)
            h="Fail";
        String update="Update Student set ID='"+jTextField2.getText()+"',Name='"+jTextField1.getText()+"',Gender='"+jTextField3.getText()+"',Session='"+jTextField4.getText()+"',Punctuality='"+jTextField5.getText()+"',Discipline='"+jTextField17.getText()+"',Leadership='"+jTextField6.getText()+"',Interaction='"+jTextField7.getText()+"',Neatness='"+jTextField8.getText()+"',Understanding='"+jTextField9.getText()+"',Politeness='"+jTextField10.getText()+"',Code_Of_Conduct='"+jTextField11.getText()+"',Pronunciation='"+jTextField12.getText()+"',Clarity='"+jTextField13.getText()+"',Confidence='"+jTextField14.getText()+"',Communication_Of_Ideas='"+jTextField15.getText()+"',Originality='"+jTextField16.getText()+"',Pointer="+pointer+",Evaluation='"+h+"' where ID='"+jTextField2.getText()+"' and Session='"+jTextField4.getText()+"'";
          try
        {
          pst=con.prepareStatement(update);
          System.out.println(pst);
          pst.execute();
         // rs=pst.executeQuery();
          
          JOptionPane.showMessageDialog(null,"Edited");
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
       e.printStackTrace();
        }
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String x=jTextField18.getText(); 
int x1=Integer.parseInt(x);
String y=jComboBox1.getSelectedItem().toString();
String z=jComboBox2.getSelectedItem().toString();
Rankings r=new Rankings();
r.Update_Table(x1,y,z);
r.setVisible(true);
r.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String x=jTextField19.getText(); 
String y=jTextField20.getText();
int x1=Integer.parseInt(x);
String sql="Select Punctuality,Discipline,Leadership,Interaction,Neatness,Understanding,Politeness,Code_Of_Conduct,Pronunciation,Clarity,Confidence,Communication_Of_Ideas,Originality from Student where Session="+x1+" and ID='"+y+"' ";
int w=0,w1=0,w2=0,w3=0,w4=0,w5=0,w6=0,w7=0,w8=0,w9=0,w10=0,w11=0,w12=0;    
try
        {
          pst=con.prepareStatement(sql);
          pst.execute();
          rs=pst.executeQuery();
           w=rs.getInt("Punctuality");
           w1=rs.getInt("Discipline");
          w2=rs.getInt("Leadership");
           w3=rs.getInt("Interaction");
           w4=rs.getInt("Neatness");
           w5=rs.getInt("Understanding");
           w6=rs.getInt("Politeness");
           w7=rs.getInt("Code_Of_Conduct");
           w8=rs.getInt("Pronunciation");
           w9=rs.getInt("Clarity");
           w10=rs.getInt("Confidence");
           w11=rs.getInt("Communication_Of_Ideas");
           w12=rs.getInt("Originality");
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

String r=jComboBox5.getSelectedItem().toString();
DefaultCategoryDataset dataset=new DefaultCategoryDataset();

DefaultPieDataset pieDataSet=new DefaultPieDataset();

if(r.equals("Pie Chart"))
{        

pieDataSet.setValue("Punctuality", w);
pieDataSet.setValue("Discipline", w1);
pieDataSet.setValue("Leadership", w2);
pieDataSet.setValue("Interaction", w3);
pieDataSet.setValue("Neatness", w4);
pieDataSet.setValue("Understanding",w5);
pieDataSet.setValue("Politeness", w6);
pieDataSet.setValue("Code Of Conduct", w7);
pieDataSet.setValue("Pronunciation", w8);
pieDataSet.setValue("Clarity", w9);
pieDataSet.setValue("Confidence", w10);
pieDataSet.setValue("Communication Of Ideas", w11);
pieDataSet.setValue("Originality", w12);
JFreeChart chart=ChartFactory.createPieChart("Pie Chart",pieDataSet,true,true,true);
PiePlot P=(PiePlot)chart.getPlot();
//P.setForegroundAlpha(TOP_ALIGNMENT);
ChartFrame frame=new ChartFrame("Pie Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
}// TODO add your handling code here:
if(r.equals("Line Chart"))
{
dataset.setValue(w,"Values","Punctuality");
dataset.setValue(w1,"Values","Discipline");
dataset.setValue(w2,"Values","Leadership");
dataset.setValue(w3,"Values","Interaction");
dataset.setValue(w4,"Values","Neatness");
dataset.setValue(w5,"Values","Understanding");
dataset.setValue(w6,"Values","Politeness");
dataset.setValue(w7,"Values","Code_Of_Conduct");
dataset.setValue(w8,"Values","Pronunciation");
dataset.setValue(w9,"Values","Clarity");
dataset.setValue(w10,"Values","Confidence");
dataset.setValue(w11,"Values","Communication_Of_Ideas");
dataset.setValue(w12,"Values","Originality");
JFreeChart chart=ChartFactory.createLineChart("Plot","Parameters","Values",dataset,PlotOrientation.VERTICAL,false,true,false);
chart.setBackgroundPaint(Color.CYAN);
chart.getTitle().setPaint(Color.red);
CategoryPlot p=chart.getCategoryPlot();
p.setRangeGridlinePaint(Color.ORANGE);

//P.setForegroundAlpha(TOP_ALIGNMENT);
ChartFrame frame=new ChartFrame("Line Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
   
}
if(r.equals("Bar Chart"))
{
dataset.setValue(w,"Values","Punctuality");
dataset.setValue(w1,"Values","Discipline");
dataset.setValue(w2,"Values","Leadership");
dataset.setValue(w3,"Values","Interaction");
dataset.setValue(w4,"Values","Neatness");
dataset.setValue(w5,"Values","Understanding");
dataset.setValue(w6,"Values","Politeness");
dataset.setValue(w7,"Values","Code_Of_Conduct");
dataset.setValue(w8,"Values","Pronunciation");
dataset.setValue(w9,"Values","Clarity");
dataset.setValue(w10,"Values","Confidence");
dataset.setValue(w11,"Values","Communication_Of_Ideas");
dataset.setValue(w12,"Values","Originality");
JFreeChart chart=ChartFactory.createBarChart3D("Plot","Parameters","Values",dataset,PlotOrientation.VERTICAL,false,true,false);
chart.setBackgroundPaint(Color.CYAN);
chart.getTitle().setPaint(Color.red);
CategoryPlot p=chart.getCategoryPlot();
p.setRangeGridlinePaint(Color.ORANGE);

//P.setForegroundAlpha(TOP_ALIGNMENT);
ChartFrame frame=new ChartFrame("Line Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
   
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String x=jTextField21.getText(); 
String y=jTextField22.getText();
int x1=Integer.parseInt(x);
String sql="Select Punctuality,Discipline,Leadership,Interaction,Neatness,Understanding,Politeness,Code_Of_Conduct,Pronunciation,Clarity,Confidence,Communication_Of_Ideas,Originality from Student where Session="+x1+" and ID='"+y+"' ";
int w=0,w1=0,w2=0,w3=0,w4=0,w5=0,w6=0,w7=0,w8=0,w9=0,w10=0,w11=0,w12=0;    
DefaultCategoryDataset dataset=new DefaultCategoryDataset();
DefaultCategoryDataset dataset1=new DefaultCategoryDataset();

try
        {
          pst=con.prepareStatement(sql);
          pst.execute();
          rs=pst.executeQuery();
           w=rs.getInt("Punctuality");
           w1=rs.getInt("Discipline");
          w2=rs.getInt("Leadership");
           w3=rs.getInt("Interaction");
           w4=rs.getInt("Neatness");
           w5=rs.getInt("Understanding");
           w6=rs.getInt("Politeness");
           w7=rs.getInt("Code_Of_Conduct");
           w8=rs.getInt("Pronunciation");
           w9=rs.getInt("Clarity");
           w10=rs.getInt("Confidence");
           w11=rs.getInt("Communication_Of_Ideas");
           w12=rs.getInt("Originality");
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
System.out.println(w1);
String t=jTextField23.getText(); 
String u=jTextField24.getText();
int t1=Integer.parseInt(t);
String sql1="Select Punctuality,Discipline,Leadership,Interaction,Neatness,Understanding,Politeness,Code_Of_Conduct,Pronunciation,Clarity,Confidence,Communication_Of_Ideas,Originality from Student where Session="+t1+" and ID='"+u+"' ";
int q=0,q1=0,q2=0,q3=0,q4=0,q5=0,q6=0,q7=0,q8=0,q9=0,q10=0,q11=0,q12=0;    
try
        {
          pst=con.prepareStatement(sql1);
          pst.execute();
          rs=pst.executeQuery();
           q=rs.getInt("Punctuality");
           q1=rs.getInt("Discipline");
          q2=rs.getInt("Leadership");
           q3=rs.getInt("Interaction");
           q4=rs.getInt("Neatness");
           q5=rs.getInt("Understanding");
           q6=rs.getInt("Politeness");
           q7=rs.getInt("Code_Of_Conduct");
           q8=rs.getInt("Pronunciation");
           q9=rs.getInt("Clarity");
           q10=rs.getInt("Confidence");
           q11=rs.getInt("Communication_Of_Ideas");
           q12=rs.getInt("Originality");
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
System.out.println(q);
dataset.setValue(w,"Values","Punctuality");
dataset.setValue(w1,"Values","Discipline");
dataset.setValue(w2,"Values","Leadership");
dataset.setValue(w3,"Values","Interaction");
dataset.setValue(w4,"Values","Neatness");
dataset.setValue(w5,"Values","Understanding");
dataset.setValue(w6,"Values","Politeness");
dataset.setValue(w7,"Values","Code_Of_Conduct");
dataset.setValue(w8,"Values","Pronunciation");
dataset.setValue(w9,"Values","Clarity");
dataset.setValue(w10,"Values","Confidence");
dataset.setValue(w11,"Values","Communication_Of_Ideas");
dataset.setValue(w12,"Values","Originality");
dataset.setValue(q,"Values1","Punctuality");
dataset.setValue(q1,"Values1","Discipline");
dataset.setValue(q2,"Values1","Leadership");
dataset.setValue(q3,"Values1","Interaction");
dataset.setValue(q4,"Values1","Neatness");
dataset.setValue(q5,"Values1","Understanding");
dataset.setValue(q6,"Values1","Politeness");
dataset.setValue(q7,"Values1","Code_Of_Conduct");
dataset.setValue(q8,"Values1","Pronunciation");
dataset.setValue(q9,"Values1","Clarity");
dataset.setValue(q10,"Values1","Confidence");
dataset.setValue(q11,"Values1","Communication_Of_Ideas");
dataset.setValue(q12,"Values1","Originality");
JFreeChart chart=ChartFactory.createLineChart("Plot","Parameters","Values",dataset,PlotOrientation.VERTICAL,false,true,false);
chart.setBackgroundPaint(Color.CYAN);
chart.getTitle().setPaint(Color.red);
CategoryPlot p=chart.getCategoryPlot();
p.setRangeGridlinePaint(Color.ORANGE);

//P.setForegroundAlpha(TOP_ALIGNMENT);
ChartFrame frame=new ChartFrame("Line Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
ResultSet rs2=null;
PreparedStatement ps2=null;

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String p1=jComboBox4.getSelectedItem().toString();
        String p2=jComboBox3.getSelectedItem().toString();
        
        double a[]=new double[20];
        String x=jTextField25.getText();
        int n=0;
            String sql="Select "+p1+" from Student where ID='"+x+"' ";
            String sql2="Select count("+p1+") as total from Student where ID='"+x+"' ";
            
           try
           {
            ps2=con.prepareStatement(sql2);
            ps2.execute();
            rs2=ps2.executeQuery();
            n=rs2.getInt("total");
            System.out.println(sql);
           }
           catch(Exception e)
           {
            JOptionPane.showMessageDialog(null,e);
               
           }
            
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        DefaultPieDataset pieDataSet=new DefaultPieDataset();

        int i=0;
        try
        {
  
        pst=con.prepareStatement(sql);
        pst.execute();
        rs=pst.executeQuery();
          while(rs.next())
        {
             

         a[i]=rs.getDouble(p1);
         i++;
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    String j="Session";
    int j1=0;
    for(i=0;i<n;i++)
    {
    StringBuilder sb=new StringBuilder();
    sb=sb.append(j);
    sb.append(" ");
    j1=i+1;
    sb.append(j1);
    dataset.setValue(a[i],"Values",sb.toString());
    pieDataSet.setValue(sb.toString(), a[i]);
    }

    if(p2.equals("Pie Chart"))
    {        

    JFreeChart chart=ChartFactory.createPieChart("Pie Chart",pieDataSet,true,true,true);
    PiePlot P=(PiePlot)chart.getPlot();
//P.setForegroundAlpha(TOP_ALIGNMENT);
    ChartFrame frame=new ChartFrame("Pie Chart",chart);
    frame.setVisible(true);
    frame.setSize(450,500);
    }
    if(p2.equals("Line Chart"))
    {
    JFreeChart chart=ChartFactory.createLineChart("Plot","Parameters","Values",dataset,PlotOrientation.VERTICAL,false,true,false);
    chart.setBackgroundPaint(Color.CYAN);
    chart.getTitle().setPaint(Color.red);
    CategoryPlot p=chart.getCategoryPlot();
    p.setRangeGridlinePaint(Color.ORANGE);

//P.setForegroundAlpha(TOP_ALIGNMENT);
    ChartFrame frame=new ChartFrame("Line Chart",chart);
    frame.setVisible(true);
    frame.setSize(450,500);
    }
if(p2.equals("Bar Chart"))
{
JFreeChart chart=ChartFactory.createBarChart3D("Plot","Parameters","Values",dataset,PlotOrientation.VERTICAL,false,true,false);
chart.setBackgroundPaint(Color.CYAN);
chart.getTitle().setPaint(Color.red);
CategoryPlot p=chart.getCategoryPlot();
p.setRangeGridlinePaint(Color.ORANGE);

//P.setForegroundAlpha(TOP_ALIGNMENT);
ChartFrame frame=new ChartFrame("Line Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
}


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jTextField9.setText("");
jTextField10.setText("");
jTextField11.setText("");
jTextField12.setText("");
jTextField13.setText("");
jTextField14.setText("");
jTextField15.setText("");
jTextField16.setText("");
jTextField17.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
